# Services for Discord Webhook integration
send_message:
  name: Send message
  description: Send a message to a Discord webhook
  fields:
    message:
      name: Message
      description: The message to send
      required: true
      example: "Hello from Home Assistant"
    username:
      name: Username
      description: Override the default username for this message
      required: false
      example: "Home Assistant Bot"
    avatar_url:
      name: Avatar URL
      description: Override the default avatar URL for this message
      required: false
      example: "https://www.home-assistant.io/images/favicon-192x192-full.png"
    tts:
      name: Text-to-speech
      description: Whether to use text-to-speech for this message
      required: false
      default: false
      example: false
    data:
      name: Additional data
      description: Additional data including images and embeds
      required: false
      example:
        images:
          - "https://example.com/image1.jpg"
        tts: true
